### ISSUE TITLE
will there be a feature to allow specifying conditions for each operation?

### ISSUE THREAD

**Issue by xshadowlegendx** [ihippik/wal-listener#48]
sth similar to below

```yaml
databases:
  filter:
    tables:
      users:
        - insert
        - operation: update
          conditions: row.status == 'active' && row.contains('general') # google cel
```

I can make a pr for this if it is allowed
